# No incluir version: '3.8' ya que es obsoleto en versiones nuevas de Docker

services:
  # Servicio de la base de datos MySQL
  db:
    image: mysql:8.0
    container_name: acasia_db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-cadep}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
    volumes:
      - db_data:/var/lib/mysql
    command: >
      --default-authentication-plugin=mysql_native_password
      --bind-address=0.0.0.0
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      timeout: 20s
      retries: 5
      start_period: 30s
      interval: 15s

  # Servicio de phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: acasia_phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
    depends_on:
      db:
        condition: service_healthy

# Definición del volumen nombrado para la persistencia de los datos de MySQL
volumes:
  db_data: